name = "Guition P4"
chip = "esp32p4"
target = "riscv32imafc-esp-espidf"
sdkconfig = ["sdkconfig.defaults", "sdkconfig.board.guition-p4"]
bootloader = "bootloaders/esp32p4.bin"
features = ["esp32", "nic-eth", "sdcard"]
default_baud = 460800
description = "Guition JC-ESP32P4-M3-DEV (Ethernet, 32MB PSRAM, 16MB flash)"
